### ISSUE TITLE
Friendly message for GET requests to the hub URL

### ISSUE THREAD

**Issue by aaronpk** [cweiske/phubb#1]
Currently the other hubs have a helpful page when a GET request is made to the hub URL, so that people clicking links in docs or HTML tags can see more information about how to use the hub. It would be great if phubb did the same!
- http://pubsubhubbub.appspot.com
- https://pubsubhubbub.superfeedr.com
- https://switchboard.p3k.io

**Comment by cweiske** [comment]
Implemented:
- http://phubb.cweiske.de/
- http://phubb.cweiske.de/hub.php
