### ISSUE TITLE
feedbin.com subscription 404s

### ISSUE THREAD

**Issue by cweiske** [cweiske/phubb#7]
The log has too many of the same entries:

    Aug 15 20:23:51 ahso2 phubb-worker.php[3284]: PHP Warning:  
    file_get_contents(https://feedbin.com/feeds/1301106/push?hub.mode=subscribe&hub.topic=http%3A%2F%2Fcweiske.de%2Ftagebuch%2Ffeed%2F&hub.challenge=foo&hub.lease_seconds=608400):
    failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found

**Comment by pstuifzand** [comment]
I think you need hub.secret -> hub.verify_token in there. Perhaps this helps: https://github.com/feedbin/feedbin/blob/master/app/controllers/feeds_controller.rb#L50

**Comment by cweiske** [comment]
In that case, `hub.verify_token` needs to be set in the callback URL already.
The spec does not define that parameter: https://www.w3.org/TR/websub/#x5-3-hub-verifies-intent-of-the-subscriber

**Comment by cweiske** [comment]
FeedBin does not seem to support WebSub anymore (I registered a test account, subscribed to http://push-tester.cweiske.de/ but my hub did not get a subscription request from feedbin).

Closing for now.
